apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "my-service"
  replicas: 2
  selector:
    matchLabels:
      app:  web
  template:
    metadata:
      labels:
        app:  web
    spec:
      containers:
      - name: think-replica
        image: sumanthc/node-js_routes:latest
        env:
        - name: CHECK
          value: "1"
        ports:
        - containerPort: 3000
          name: web
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds:  10
        readinessProbe:
          tcpSocket: 
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          requests:
            memory: "24M"
            cpu:  "150m"
          limits:
            memory: "32M"
            cpu: "250m"


    
